.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. sagbit_qt test_sagbit_qt
clean: FORCE
	$(MAKE) -C .. sagbit_qt_clean test_sagbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_sagbit_qt_check
sagbit-qt sagbit-qt.exe: FORCE
	 $(MAKE) -C .. sagbit_qt
